# Site settings

url: "http://jyhong.com"
title: "Junyuan Hong"
author: "Junyuan Hong"
description: "Blog and website of Junyuan Hong, blogging mainly for tech. Opinions expressed are mine."
keywords: "jyhong, junyuan, hong, junyuan hong, technology, computer science"

google-tracking-id: "UA-59631745-2"
disqus-shortname: "hongblog"
markdown: redcarpet
highlighter: pygments
redcarpet:
  extensions: ["with_toc_data", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "highlight", "quote", "underline", "footnotes", "prettify"]
kramdown:
  # input:          GFM
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: true
  syntax_highlighter: pygments

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               class

# favicon

favicon: "/img/icon/icon_64x64.png"
black-favicon: "/img/icon/icon_64x64.png"

favicon-16x16: "/img/icon/icon_16x16.png"
favicon-32x32: "/img/icon/icon_32x32.png"
favicon-64x64: "/img/icon/icon_64x64.png"
favicon-96x96: "/img/icon/icon_96x96.png"
favicon-57x57: "/img/icon/icon_57x57.png"
favicon-114x114: "/img/icon/icon_114x114.png"
favicon-72x72: "/img/icon/icon_72x72.png"
favicon-144x144: "/img/icon/icon_144x144.png"
favicon-60x60: "/img/icon/icon_60x60.png"
favicon-120x120: "/img/icon/icon_120x120.png"
favicon-76x76: "/img/icon/icon_76x76.png"
favicon-152x152: "/img/icon/icon_152x152.png"

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Blog: 'blog'
  Career: 'career'
  Work: 'work'
  Contact: 'contact'

background-img: "/img/intro-bg.jpg"

# About variables

me-img: "/img/me.jpg"

# Blog variables
paginate: 15

paginate_path: "blog/page:num"

post-preview-words: 128

fb-share: True
twitter-share: True
reddit-share: False

# Work variables

works:
  - url: "/MarkdownAttribute"
    title: "Markdown Attribute"
    # image: "img/work/jacie.jpg"
    date: "October 2015"
    description: "Parser for converting Markdown to pretty NSAttributedString"
    labels: ["Swift", "Cocoa", "Markdown"]
  - url: "/Vivi"
    title: "Vivi"
    # image: "img/work/jacie.jpg"
    date: "July 2015"
    description: "XMPP chat client on OS X"
    labels: ["Swift", "Cocoa", "XMPP"]
  - url: "/jacie"
    title: "Jacie"
    image: "img/work/jacie.jpg"
    date: "January 2014"
    description: "A chat robot based on AIML"
    labels: ["Python", "AIML"]
  - url: "/draw3d"
    title: "Draw3D"
    image: "img/work/draw3d.jpg"
    date: "March 2014"
    description: "3d model program using basic Java graphic APIs"
    labels: ["Java", "3D"]

# First image of the Work timeline
work-line:
  first-img: "/img/work/default.jpg"
  limit-num: 5

# Career variables

events:
  # - image: "/img/career/ustc.jpg"
  #   date: "September 2015 - Today"
  #   description: "Computer Science Master @ University of Science and Technology of China, working @ the <a href=\"http://dev.office.com/officegraph\" target=\"_blank\"> Office Graph</a>"
  # - image: "/img/career/uoa.jpg"
  #   date: "October 2012 - August 2014"
  #   description: "Master studies @ <a href=\"http://www.di.uoa.gr/eng\" target=\"_blank\">Department of Informatics and Telecommunications</a> on Software Engineering + <a href=\"http://scholar.google.com/citations?user=UtV6LFYAAAAJ&amp;hl=en&amp;oi=ao\" target=\"_blank\">Machine Learning researcher</a> @ <a href=\"http://kddlab.di.uoa.gr\" target=\"_blank\">KDD</a> lab"
  # - image: "/img/career/cern.jpg"
  #   date: "October 2011 - September 2012"
  #   description: "Security researcher @ <a href=\"http://www.cern.ch\" target=\"_blank\">CERN</a>, developed linux kernel extensions to prevent cyber attacks"
  # - image: "/img/career/writeright.jpg"
  #   date: "August 2011 - Today"
  #   description: "Released <a href=\"https://play.google.com/store/apps/details?id=panos.sakkos.softkeyboard.writeright\" target=\"_blank\">WriteRight</a>, an adaptive S/W keyboard for Android devices, which  shrinks the unlikely keys to tap next. Currently it holds &gt; 9,000 downloads"
  # - image: "/img/career/pwnmail.jpg"
  #   date: "June 2010 - November 2010"
  #   description: "Released <a href=\"https://www.google.com/search?q=pwn+mail\" target=\"_blank\">Pwn Mail</a>, an iPhone app for spoofing emails. It served &gt; 260,000 emails but it was discontinued after a legal threat by <strike>Steve Jobs</strike> a secretary of Steve Jobs"
  - image: "/img/career/ustc.jpg"
    date: "September 2015 - Today"
    description: "Master studies @ <a href=\"http://ubri.ustc.edu.cn\" target=\"_blank\">USTC-Birmingham Joint Research Institute</a> on Intelligent Computing and Application"
  - image: "/img/career/ustc.jpg"
    date: "September 2011 - June 2015"
    description: "Bachelor studies @ <a href=\"http://en.physics.ustc.edu.cn/departments/Dept_of_Optics/\" target=\"_blank\">Department of Optics and Optical Engineering</a> on Optics"

# First image of the Career timeline
career-img: "/img/career/default.jpg"

# Social networks variables (many more available: facebook, flickr, dribbble, pinterest, instagram, tumblr etc.)
social:
  - title: "rss"
    url: "/feed.xml"
  - title: "github"
    url: "https://github.com/jyhong836"
  # - title: "google-plus"
  #   url: "https://plus.google.com/u/0/113310389738293078885/posts"
  # - title: "twitter"
  #   url: "https://twitter.com/hjy836"
  - title: "linkedin"
    url: "http://cn.linkedin.com/in/jyhong836"
  # - title: "youtube"
  #   url: "https://www.youtube.com/channel/UCod6Ld7_Rby80QN-5w1FhQA"
  # - title: "soundcloud"
  #   url: "https://soundcloud.com/psakkos/"

404-img: "/img/labtocat.png"

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
